MODEL:
  NUM_CLASSES: 21
  PRIORS:
    FEATURE_MAPS: [40, 20, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 107, 320]
    MIN_SIZES: [21, 45, 99, 153, 207, 261]
    MAX_SIZES: [45, 99, 153, 207, 261, 315]
    ASPECT_RATIOS: [[1.6, 2, 3], [1.6, 2, 3], [1.6, 2, 3], [1.6, 2, 3], [1.6, 2, 3], [1.6, 2, 3]]
    BOXES_PER_LOCATION: [8, 8, 8, 8, 8, 8]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: 'outputs/resnet101_dssd320_voc0712'